version: '3.7'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mysql
    environment:
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DB_PASSWORD: $DB_PASSWORD
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG_DISPLAY', false );
        define( 'WP_DEBUG_LOG', true );
        define( 'SAVEQUERIES', true );
    volumes:
      - ./html:/var/www/html/
      - "./${COMPOSE_PROJECT_NAME}/:/var/www/html/wp-content/themes/${COMPOSE_PROJECT_NAME}/"
      - ./ssl/localhost.crt:/etc/apache2/ssl/localhost.crt
      - ./ssl/localhost.key:/etc/apache2/ssl/localhost.key
      - ./ssl/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./ssl/ssl.load:/etc/apache2/mods-enabled/ssl.load

  mysql:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD

volumes:
  data:
