version: '3.7'

services:
  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mysql
    environment: &enviro
      WORDPRESS_TABLE_PREFIX: ${DB_PREFIX:-wp_}
      WORDPRESS_DB_USER: ${DB_USER:-root}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-simplepassword}
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG_DISPLAY', false );
        define( 'SAVEQUERIES', true );
        define( 'SCRIPT_DEBUG', true );
        define( 'CONCATENATE_SCRIPTS', false );
        define( 'JETPACK_DEV_DEBUG', true );
    volumes: &anchor
      - "./${THEME_FOLDER:-some-theme}/:/var/www/html/wp-content/themes/${THEME_FOLDER:-some-theme}/"
      - ./dev/files/html:/var/www/html/
      - ./dev/files/ssl/localhost.crt:/etc/apache2/ssl/localhost.crt
      - ./dev/files/ssl/localhost.key:/etc/apache2/ssl/localhost.key
      - ./dev/ssl/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./dev/ssl/ssl.load:/etc/apache2/mods-enabled/ssl.load
      - ./dev/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./dev/mu-plugins/fix-loopback.php:/var/www/html/wp-content/mu-plugins/fix-loopback.php

  mysql:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./dev/initdb:/docker-entrypoint-initdb.d
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-simplepassword}
      MYSQL_DATABASE: wordpress

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-simplepassword}
    volumes:
      - ./dev/uploads.ini:/usr/local/etc/php/php.ini

  cli:
    image: wordpress:cli
    depends_on:
      - wordpress
    volumes: *anchor
    user: "33:33"
    environment: *enviro

volumes:
  data:
